[package]
name = "downloader"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The _lib suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "downloader_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7", features = ["rt"] }
reqwest = { version = "0.13", default-features = false, features = ["stream", "rustls", "http2"] }
futures-util = "0.3"
blake3 = "1"
sha2 = "0.10"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
sanitize-filename = "0.5"
thiserror = "1"
uuid = { version = "1", features = ["v4", "serde"] }
urlencoding = "2"
tauri-plugin-dialog = "2"
mimalloc = "0.1.48"
fs4 = { version = "0.13", features = ["sync"] }
librqbit = "8.1.1"
ssh2 = "0.9"

[dev-dependencies]
axum = "0.8"
tempfile = "3"
